### ISSUE TITLE
config.txt Werte

### ISSUE THREAD

**Issue by dmqgit** [jp112sdl/GSM_Spannungswaechter#1]
Hallo,

danke für das Projekt. Ich habe alles soweit nachgebaut. Mir fehlt nur noch die SIM Karte. Ich habe eine Frage zu den Werten in der config.txt. Reicht es, wenn ich die config.txt JSON-formatiert folgendermaßen anlege:

```
{
  "ACPOWERUPMINS": "1",
  "ACPOWERDOWNMINS": "0",
  "COSTPERSMS": "30",
  "ACPOWERUPMESSAGE": "Strom da",
  "ACPOWERDOWNMESSAGE": "Stom weg",
  "SMSRECEIVER[1]": "+491....",
  "SMSRECEIVER[2]": "+491....
}
```
Auf dem OLED bleibt die Angabe des Textes mit "Warte auf GSM" stehen. Code-technisch sollte als nächstes das Array mit den SMSRECEIVER durchlaufen werden.

Habe ich es richtig eingetragen? Oder kannst Du mal ein Beispiel einstellen?

Danke Dir vielmals

**Comment by jp112sdl** [comment]
Du brauchst keine Datei anlegen.
Wenn du den Spannungswächter im AP-Modus startest, kannst du alles übers Web konfigurieren.

Der Code bzw. das Projekt ist schon sehr alt. Ich habe es nicht weiter gepflegt und nur 1 Gerät gebaut, geflasht und fertig.
Ob das alles noch so kompatibel ist mit den neuesten Lib Versionen , kann ich dir nicht sagen

**Comment by dmqgit** [comment]
Danke für die schnelle Antwort :+1: 

Wenn ich keine config.txt per SPIFFS-Upload mit lade, kommt anfangs ein LoadConfig Error und es ist auch nicht möglich in den Config-Modus per Button zu kommen.

Wenn ich die Config wie o.a. f mitgebe (CaseSensitivity habe ich auch beachtet), kommt es im Web-GUI zu Fehlern - siehe Bild. Ich habe die Werte für die Variablen SMSRECEIVER[i] auch schon komplett herausgenommen. Ich vermute ich habe sie nicht richtig angegeben.

Die Libraries sind nach ein wenig Anpassung (ältere Version eingespielt) noch soweit in Ordnung. 

Hast Du eine Idee?

![screen](https://user-images.githubusercontent.com/33730807/64066690-5002f600-cc1d-11e9-8af8-cdfe5dd1bcc4.png)

**Comment by dmqgit** [comment]
Es ist jetzt in Ordnung. Ich habe die Website einfach mit "OK" bestätigt. Im Anschluss wird ein Neustart erzwungen. Danach waren werden die Variablen korrekt auf dem OLED angezeigt. Im Anschluss kann ich dann auch alles normal im ConfigMode setzen.

Danke Dir nochmal!
