### ISSUE TITLE
A0 5V tolerant - Spannungsteiler?

### ISSUE THREAD

**Issue by dmqgit** [jp112sdl/GSM_Spannungswaechter#2]
Hi,

ich habe das System komplett nach Wiring-Guide nachgebaut. Du hast in dem Wiring-Example einen 100k Widerstand an A0 gesetzt. Hast Du das Ganze an der Stelle mit einer 5V Spannung laufen, oder hast Du ein 3.3V Netzteil oder einen Spannungsteiler im Einsatz?

Danke Dir

**Comment by jp112sdl** [comment]
Ich habe das so mit 5V laufen.
Dient lediglich der Erkennung, ob extern noch Spannung anliegt.
Der Wemos hat bereits einen eingebauten Teiler:
https://www.nikolaus-lueneburg.de/2016/12/spannungsteiler/

**Comment by dmqgit** [comment]
Danke Dir!
